//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork.Multilingual {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AtWork.Multilingual.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string InternalServerErrorMsg {
            get {
                return ResourceManager.GetString("InternalServerErrorMsg", resourceCulture);
            }
        }
        
        internal static string UnauthorizedErrorMsg {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMsg", resourceCulture);
            }
        }
        
        internal static string RequestTimeoutErrorMsg {
            get {
                return ResourceManager.GetString("RequestTimeoutErrorMsg", resourceCulture);
            }
        }
        
        internal static string SomethingWentWrongText {
            get {
                return ResourceManager.GetString("SomethingWentWrongText", resourceCulture);
            }
        }
        
        internal static string TooManyAttemptsText {
            get {
                return ResourceManager.GetString("TooManyAttemptsText", resourceCulture);
            }
        }
        
        internal static string BackendErrorText {
            get {
                return ResourceManager.GetString("BackendErrorText", resourceCulture);
            }
        }
        
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        internal static string AlertOkText {
            get {
                return ResourceManager.GetString("AlertOkText", resourceCulture);
            }
        }
        
        internal static string NoInternetMsg {
            get {
                return ResourceManager.GetString("NoInternetMsg", resourceCulture);
            }
        }
        
        internal static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        internal static string StartWritingYourPost {
            get {
                return ResourceManager.GetString("StartWritingYourPost", resourceCulture);
            }
        }
        
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        internal static string CommentPlaceholderText {
            get {
                return ResourceManager.GetString("CommentPlaceholderText", resourceCulture);
            }
        }
        
        internal static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        internal static string AddImagesToYourPost {
            get {
                return ResourceManager.GetString("AddImagesToYourPost", resourceCulture);
            }
        }
        
        internal static string AddAttachFileToYourPost {
            get {
                return ResourceManager.GetString("AddAttachFileToYourPost", resourceCulture);
            }
        }
        
        internal static string StoragePermissionAlert {
            get {
                return ResourceManager.GetString("StoragePermissionAlert", resourceCulture);
            }
        }
        
        internal static string PermissionErrorText {
            get {
                return ResourceManager.GetString("PermissionErrorText", resourceCulture);
            }
        }
        
        internal static string EditCropButtonText {
            get {
                return ResourceManager.GetString("EditCropButtonText", resourceCulture);
            }
        }
        
        internal static string ChooseWhoCanSeeYourPost {
            get {
                return ResourceManager.GetString("ChooseWhoCanSeeYourPost", resourceCulture);
            }
        }
        
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        internal static string DeleteCommentMessage {
            get {
                return ResourceManager.GetString("DeleteCommentMessage", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        internal static string ChooseFromCameraRoll {
            get {
                return ResourceManager.GetString("ChooseFromCameraRoll", resourceCulture);
            }
        }
        
        internal static string NewsFooterText {
            get {
                return ResourceManager.GetString("NewsFooterText", resourceCulture);
            }
        }
        
        internal static string ActivitiesFooterText {
            get {
                return ResourceManager.GetString("ActivitiesFooterText", resourceCulture);
            }
        }
        
        internal static string PulseFooterText {
            get {
                return ResourceManager.GetString("PulseFooterText", resourceCulture);
            }
        }
        
        internal static string JoinActivityText {
            get {
                return ResourceManager.GetString("JoinActivityText", resourceCulture);
            }
        }
        
        internal static string AboutActivityHeaderText {
            get {
                return ResourceManager.GetString("AboutActivityHeaderText", resourceCulture);
            }
        }
        
        internal static string MinGroupText {
            get {
                return ResourceManager.GetString("MinGroupText", resourceCulture);
            }
        }
        
        internal static string MaxGroupText {
            get {
                return ResourceManager.GetString("MaxGroupText", resourceCulture);
            }
        }
        
        internal static string TimeText {
            get {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }
        
        internal static string CostsCoveredByCompanyText {
            get {
                return ResourceManager.GetString("CostsCoveredByCompanyText", resourceCulture);
            }
        }
        
        internal static string CostsCoveredByEmployeeText {
            get {
                return ResourceManager.GetString("CostsCoveredByEmployeeText", resourceCulture);
            }
        }
        
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        internal static string CommentsText {
            get {
                return ResourceManager.GetString("CommentsText", resourceCulture);
            }
        }
        
        internal static string ActivityTypeText {
            get {
                return ResourceManager.GetString("ActivityTypeText", resourceCulture);
            }
        }
        
        internal static string SkillsText {
            get {
                return ResourceManager.GetString("SkillsText", resourceCulture);
            }
        }
        
        internal static string GoalText {
            get {
                return ResourceManager.GetString("GoalText", resourceCulture);
            }
        }
        
        internal static string SpecialrequirementsText {
            get {
                return ResourceManager.GetString("SpecialrequirementsText", resourceCulture);
            }
        }
        
        internal static string AboutOrganixationHeaderText {
            get {
                return ResourceManager.GetString("AboutOrganixationHeaderText", resourceCulture);
            }
        }
        
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        internal static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        internal static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        internal static string ShareThisActivityText {
            get {
                return ResourceManager.GetString("ShareThisActivityText", resourceCulture);
            }
        }
        
        internal static string MoreInformationHeaderText {
            get {
                return ResourceManager.GetString("MoreInformationHeaderText", resourceCulture);
            }
        }
        
        internal static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        internal static string MyActivitiesHeaderText {
            get {
                return ResourceManager.GetString("MyActivitiesHeaderText", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        internal static string ChooseFromCameraRole {
            get {
                return ResourceManager.GetString("ChooseFromCameraRole", resourceCulture);
            }
        }
        
        internal static string ActivityText {
            get {
                return ResourceManager.GetString("ActivityText", resourceCulture);
            }
        }
        
        internal static string PostText {
            get {
                return ResourceManager.GetString("PostText", resourceCulture);
            }
        }
        
        internal static string ImageSelectionAlertText {
            get {
                return ResourceManager.GetString("ImageSelectionAlertText", resourceCulture);
            }
        }
        
        internal static string ThankYouSigningupText {
            get {
                return ResourceManager.GetString("ThankYouSigningupText", resourceCulture);
            }
        }
        
        internal static string WhatDateYouPlanToAttendText {
            get {
                return ResourceManager.GetString("WhatDateYouPlanToAttendText", resourceCulture);
            }
        }
        
        internal static string PostDataAlertText {
            get {
                return ResourceManager.GetString("PostDataAlertText", resourceCulture);
            }
        }
        
        internal static string SkipText {
            get {
                return ResourceManager.GetString("SkipText", resourceCulture);
            }
        }
        
        internal static string PublishText {
            get {
                return ResourceManager.GetString("PublishText", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string DeletePostAlert {
            get {
                return ResourceManager.GetString("DeletePostAlert", resourceCulture);
            }
        }
        
        internal static string AcceptDisclaimer {
            get {
                return ResourceManager.GetString("AcceptDisclaimer", resourceCulture);
            }
        }
        
        internal static string AcceptTermsAndConditionsText {
            get {
                return ResourceManager.GetString("AcceptTermsAndConditionsText", resourceCulture);
            }
        }
        
        internal static string EnterSamePasswordText {
            get {
                return ResourceManager.GetString("EnterSamePasswordText", resourceCulture);
            }
        }
        
        internal static string MyActivitesText {
            get {
                return ResourceManager.GetString("MyActivitesText", resourceCulture);
            }
        }
        
        internal static string PastActivitiesText {
            get {
                return ResourceManager.GetString("PastActivitiesText", resourceCulture);
            }
        }
        
        internal static string CreateAGetTogetherText {
            get {
                return ResourceManager.GetString("CreateAGetTogetherText", resourceCulture);
            }
        }
        
        internal static string AllCategoriesText {
            get {
                return ResourceManager.GetString("AllCategoriesText", resourceCulture);
            }
        }
        
        internal static string CorporateVolunteeringText {
            get {
                return ResourceManager.GetString("CorporateVolunteeringText", resourceCulture);
            }
        }
        
        internal static string SportsText {
            get {
                return ResourceManager.GetString("SportsText", resourceCulture);
            }
        }
        
        internal static string EducationsText {
            get {
                return ResourceManager.GetString("EducationsText", resourceCulture);
            }
        }
        
        internal static string CultureText {
            get {
                return ResourceManager.GetString("CultureText", resourceCulture);
            }
        }
        
        internal static string CompanyEventsText {
            get {
                return ResourceManager.GetString("CompanyEventsText", resourceCulture);
            }
        }
        
        internal static string GetTogetherText {
            get {
                return ResourceManager.GetString("GetTogetherText", resourceCulture);
            }
        }
        
        internal static string ActivityTitle {
            get {
                return ResourceManager.GetString("ActivityTitle", resourceCulture);
            }
        }
        
        internal static string PlaceholderActivityDescription {
            get {
                return ResourceManager.GetString("PlaceholderActivityDescription", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string PriceOrPaymentPerPerson {
            get {
                return ResourceManager.GetString("PriceOrPaymentPerPerson", resourceCulture);
            }
        }
        
        internal static string ActivityDataAlertText {
            get {
                return ResourceManager.GetString("ActivityDataAlertText", resourceCulture);
            }
        }
        
        internal static string AddaCoverForYour {
            get {
                return ResourceManager.GetString("AddaCoverForYour", resourceCulture);
            }
        }
        
        internal static string Orpickoneofours {
            get {
                return ResourceManager.GetString("Orpickoneofours", resourceCulture);
            }
        }
        
        internal static string InvitePeopleToYourActivity {
            get {
                return ResourceManager.GetString("InvitePeopleToYourActivity", resourceCulture);
            }
        }
        
        internal static string AreYouSureText {
            get {
                return ResourceManager.GetString("AreYouSureText", resourceCulture);
            }
        }
        
        internal static string UnSubscribeFromActivtyText {
            get {
                return ResourceManager.GetString("UnSubscribeFromActivtyText", resourceCulture);
            }
        }
        
        internal static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        internal static string LinkCopiedText {
            get {
                return ResourceManager.GetString("LinkCopiedText", resourceCulture);
            }
        }
        
        internal static string YourFeedbackText {
            get {
                return ResourceManager.GetString("YourFeedbackText", resourceCulture);
            }
        }
        
        internal static string OverallExperienceText {
            get {
                return ResourceManager.GetString("OverallExperienceText", resourceCulture);
            }
        }
        
        internal static string ImpactOfYourVolunteeringText {
            get {
                return ResourceManager.GetString("ImpactOfYourVolunteeringText", resourceCulture);
            }
        }
        
        internal static string LikelihoodOfRecommendingText {
            get {
                return ResourceManager.GetString("LikelihoodOfRecommendingText", resourceCulture);
            }
        }
        
        internal static string HowDidYouFeelDuringTheActivityText {
            get {
                return ResourceManager.GetString("HowDidYouFeelDuringTheActivityText", resourceCulture);
            }
        }
        
        internal static string WhatNeedsToImproveText {
            get {
                return ResourceManager.GetString("WhatNeedsToImproveText", resourceCulture);
            }
        }
        
        internal static string WhatDidYouLikeMostText {
            get {
                return ResourceManager.GetString("WhatDidYouLikeMostText", resourceCulture);
            }
        }
        
        internal static string AnythingElseYouWantToAddText {
            get {
                return ResourceManager.GetString("AnythingElseYouWantToAddText", resourceCulture);
            }
        }
        
        internal static string SubmitFeedBackText {
            get {
                return ResourceManager.GetString("SubmitFeedBackText", resourceCulture);
            }
        }
        
        internal static string HappyText {
            get {
                return ResourceManager.GetString("HappyText", resourceCulture);
            }
        }
        
        internal static string CuriousText {
            get {
                return ResourceManager.GetString("CuriousText", resourceCulture);
            }
        }
        
        internal static string FullfilledText {
            get {
                return ResourceManager.GetString("FullfilledText", resourceCulture);
            }
        }
        
        internal static string TiredText {
            get {
                return ResourceManager.GetString("TiredText", resourceCulture);
            }
        }
        
        internal static string BoredText {
            get {
                return ResourceManager.GetString("BoredText", resourceCulture);
            }
        }
        
        internal static string ExcitedText {
            get {
                return ResourceManager.GetString("ExcitedText", resourceCulture);
            }
        }
        
        internal static string AnnoyedText {
            get {
                return ResourceManager.GetString("AnnoyedText", resourceCulture);
            }
        }
        
        internal static string ProudText {
            get {
                return ResourceManager.GetString("ProudText", resourceCulture);
            }
        }
        
        internal static string SuprisedText {
            get {
                return ResourceManager.GetString("SuprisedText", resourceCulture);
            }
        }
        
        internal static string SatisfiedText {
            get {
                return ResourceManager.GetString("SatisfiedText", resourceCulture);
            }
        }
        
        internal static string InterestedText {
            get {
                return ResourceManager.GetString("InterestedText", resourceCulture);
            }
        }
        
        internal static string EventOrganizationText {
            get {
                return ResourceManager.GetString("EventOrganizationText", resourceCulture);
            }
        }
        
        internal static string TransportationText {
            get {
                return ResourceManager.GetString("TransportationText", resourceCulture);
            }
        }
        
        internal static string FoodAndBeverageText {
            get {
                return ResourceManager.GetString("FoodAndBeverageText", resourceCulture);
            }
        }
        
        internal static string SecurityText {
            get {
                return ResourceManager.GetString("SecurityText", resourceCulture);
            }
        }
        
        internal static string NGOPartnersText {
            get {
                return ResourceManager.GetString("NGOPartnersText", resourceCulture);
            }
        }
        
        internal static string CommunicationText {
            get {
                return ResourceManager.GetString("CommunicationText", resourceCulture);
            }
        }
        
        internal static string EverythingWasSatisfactoryText {
            get {
                return ResourceManager.GetString("EverythingWasSatisfactoryText", resourceCulture);
            }
        }
        
        internal static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        internal static string JoinActivityAlertText {
            get {
                return ResourceManager.GetString("JoinActivityAlertText", resourceCulture);
            }
        }
        
        internal static string FeedbackText {
            get {
                return ResourceManager.GetString("FeedbackText", resourceCulture);
            }
        }
        
        internal static string FeedbackMorePlaceholderText {
            get {
                return ResourceManager.GetString("FeedbackMorePlaceholderText", resourceCulture);
            }
        }
        
        internal static string LikeMostPlaceholderText {
            get {
                return ResourceManager.GetString("LikeMostPlaceholderText", resourceCulture);
            }
        }
        
        internal static string AnythingElsePlaceholderText {
            get {
                return ResourceManager.GetString("AnythingElsePlaceholderText", resourceCulture);
            }
        }
        
        internal static string MyStatsText {
            get {
                return ResourceManager.GetString("MyStatsText", resourceCulture);
            }
        }
        
        internal static string DepartmentText {
            get {
                return ResourceManager.GetString("DepartmentText", resourceCulture);
            }
        }
        
        internal static string JobTitleText {
            get {
                return ResourceManager.GetString("JobTitleText", resourceCulture);
            }
        }
        
        internal static string ClassText {
            get {
                return ResourceManager.GetString("ClassText", resourceCulture);
            }
        }
        
        internal static string AboutMeText {
            get {
                return ResourceManager.GetString("AboutMeText", resourceCulture);
            }
        }
        
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        internal static string ProfileText {
            get {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }
        
        internal static string ChangeProfilePictureText {
            get {
                return ResourceManager.GetString("ChangeProfilePictureText", resourceCulture);
            }
        }
        
        internal static string EditInterestsText {
            get {
                return ResourceManager.GetString("EditInterestsText", resourceCulture);
            }
        }
        
        internal static string EditAboutMeText {
            get {
                return ResourceManager.GetString("EditAboutMeText", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageText {
            get {
                return ResourceManager.GetString("ChangeLanguageText", resourceCulture);
            }
        }
        
        internal static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        internal static string ManageNotificationText {
            get {
                return ResourceManager.GetString("ManageNotificationText", resourceCulture);
            }
        }
        
        internal static string ProfilePictureText {
            get {
                return ResourceManager.GetString("ProfilePictureText", resourceCulture);
            }
        }
        
        internal static string StartWriting {
            get {
                return ResourceManager.GetString("StartWriting", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        internal static string CategoryDataAlertText {
            get {
                return ResourceManager.GetString("CategoryDataAlertText", resourceCulture);
            }
        }
        
        internal static string CalendarPermissionAlert {
            get {
                return ResourceManager.GetString("CalendarPermissionAlert", resourceCulture);
            }
        }
        
        internal static string JoinActivitySuccessfulText {
            get {
                return ResourceManager.GetString("JoinActivitySuccessfulText", resourceCulture);
            }
        }
        
        internal static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        internal static string WelcomeSetup1 {
            get {
                return ResourceManager.GetString("WelcomeSetup1", resourceCulture);
            }
        }
        
        internal static string WelcomeSetup2 {
            get {
                return ResourceManager.GetString("WelcomeSetup2", resourceCulture);
            }
        }
        
        internal static string ActivitiesText {
            get {
                return ResourceManager.GetString("ActivitiesText", resourceCulture);
            }
        }
        
        internal static string HoursText {
            get {
                return ResourceManager.GetString("HoursText", resourceCulture);
            }
        }
        
        internal static string AllowNotificationsTitleText {
            get {
                return ResourceManager.GetString("AllowNotificationsTitleText", resourceCulture);
            }
        }
        
        internal static string AllowNotificationsMsgText {
            get {
                return ResourceManager.GetString("AllowNotificationsMsgText", resourceCulture);
            }
        }
        
        internal static string DontAllowText {
            get {
                return ResourceManager.GetString("DontAllowText", resourceCulture);
            }
        }
        
        internal static string AllowText {
            get {
                return ResourceManager.GetString("AllowText", resourceCulture);
            }
        }
        
        internal static string MyInterests {
            get {
                return ResourceManager.GetString("MyInterests", resourceCulture);
            }
        }
        
        internal static string WelcomeSetup {
            get {
                return ResourceManager.GetString("WelcomeSetup", resourceCulture);
            }
        }
        
        internal static string BeginSetup {
            get {
                return ResourceManager.GetString("BeginSetup", resourceCulture);
            }
        }
        
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        internal static string AtWork {
            get {
                return ResourceManager.GetString("AtWork", resourceCulture);
            }
        }
        
        internal static string Whatdoyoulooklike {
            get {
                return ResourceManager.GetString("Whatdoyoulooklike", resourceCulture);
            }
        }
        
        internal static string PleaseSelectYourLanguage {
            get {
                return ResourceManager.GetString("PleaseSelectYourLanguage", resourceCulture);
            }
        }
        
        internal static string SetProfilePicture {
            get {
                return ResourceManager.GetString("SetProfilePicture", resourceCulture);
            }
        }
        
        internal static string NowScalandmove {
            get {
                return ResourceManager.GetString("NowScalandmove", resourceCulture);
            }
        }
        
        internal static string yourphotoinsidethe {
            get {
                return ResourceManager.GetString("yourphotoinsidethe", resourceCulture);
            }
        }
        
        internal static string circularfram {
            get {
                return ResourceManager.GetString("circularfram", resourceCulture);
            }
        }
        
        internal static string AboutYourSelf {
            get {
                return ResourceManager.GetString("AboutYourSelf", resourceCulture);
            }
        }
        
        internal static string WriteYourInterests {
            get {
                return ResourceManager.GetString("WriteYourInterests", resourceCulture);
            }
        }
        
        internal static string GroupMemberPost {
            get {
                return ResourceManager.GetString("GroupMemberPost", resourceCulture);
            }
        }
        
        internal static string PosttoViewEverybody {
            get {
                return ResourceManager.GetString("PosttoViewEverybody", resourceCulture);
            }
        }
        
        internal static string PostToEverybody {
            get {
                return ResourceManager.GetString("PostToEverybody", resourceCulture);
            }
        }
        
        internal static string Posttoyourgroup {
            get {
                return ResourceManager.GetString("Posttoyourgroup", resourceCulture);
            }
        }
        
        internal static string Inviteyourgroup {
            get {
                return ResourceManager.GetString("Inviteyourgroup", resourceCulture);
            }
        }
        
        internal static string MyInterestsProfile {
            get {
                return ResourceManager.GetString("MyInterestsProfile", resourceCulture);
            }
        }
        
        internal static string DisclamerText {
            get {
                return ResourceManager.GetString("DisclamerText", resourceCulture);
            }
        }
        
        internal static string TermsText {
            get {
                return ResourceManager.GetString("TermsText", resourceCulture);
            }
        }
        
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        internal static string EnteConformNewPassword {
            get {
                return ResourceManager.GetString("EnteConformNewPassword", resourceCulture);
            }
        }
        
        internal static string EnterCurrentPasswordAlert {
            get {
                return ResourceManager.GetString("EnterCurrentPasswordAlert", resourceCulture);
            }
        }
        
        internal static string EnterNewPasswordAlert {
            get {
                return ResourceManager.GetString("EnterNewPasswordAlert", resourceCulture);
            }
        }
        
        internal static string EnterConfirmNewPasswordAlert {
            get {
                return ResourceManager.GetString("EnterConfirmNewPasswordAlert", resourceCulture);
            }
        }
        
        internal static string EnterConfirmPasswordNotMatchdAlert {
            get {
                return ResourceManager.GetString("EnterConfirmPasswordNotMatchdAlert", resourceCulture);
            }
        }
        
        internal static string Currentpasswordnotmatch {
            get {
                return ResourceManager.GetString("Currentpasswordnotmatch", resourceCulture);
            }
        }
        
        internal static string Passwordchangesuccessfully {
            get {
                return ResourceManager.GetString("Passwordchangesuccessfully", resourceCulture);
            }
        }
        
        internal static string ShareAlertText {
            get {
                return ResourceManager.GetString("ShareAlertText", resourceCulture);
            }
        }
        
        internal static string CreatePasswordText {
            get {
                return ResourceManager.GetString("CreatePasswordText", resourceCulture);
            }
        }
        
        internal static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        internal static string ClaimInputAlertText {
            get {
                return ResourceManager.GetString("ClaimInputAlertText", resourceCulture);
            }
        }
        
        internal static string ProfileCorrectionInputAlertText {
            get {
                return ResourceManager.GetString("ProfileCorrectionInputAlertText", resourceCulture);
            }
        }
        
        internal static string DisclaimerHeaderText {
            get {
                return ResourceManager.GetString("DisclaimerHeaderText", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionHeaderText {
            get {
                return ResourceManager.GetString("TermsAndConditionHeaderText", resourceCulture);
            }
        }
        
        internal static string LogoutAlert {
            get {
                return ResourceManager.GetString("LogoutAlert", resourceCulture);
            }
        }
        
        internal static string AtWorkActivityEventText {
            get {
                return ResourceManager.GetString("AtWorkActivityEventText", resourceCulture);
            }
        }
        
        internal static string joinedText {
            get {
                return ResourceManager.GetString("joinedText", resourceCulture);
            }
        }
        
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        internal static string BiometricAlertMsgText {
            get {
                return ResourceManager.GetString("BiometricAlertMsgText", resourceCulture);
            }
        }
        
        internal static string AuthenticationText {
            get {
                return ResourceManager.GetString("AuthenticationText", resourceCulture);
            }
        }
        
        internal static string AuthenticationAlertMsgText {
            get {
                return ResourceManager.GetString("AuthenticationAlertMsgText", resourceCulture);
            }
        }
        
        internal static string AuthenticationFailedAlertMsgText {
            get {
                return ResourceManager.GetString("AuthenticationFailedAlertMsgText", resourceCulture);
            }
        }
        
        internal static string ComingSoonAlertMsgText {
            get {
                return ResourceManager.GetString("ComingSoonAlertMsgText", resourceCulture);
            }
        }
        
        internal static string Logintoyourcompany {
            get {
                return ResourceManager.GetString("Logintoyourcompany", resourceCulture);
            }
        }
        
        internal static string WouldYouLikeToEnableMsgText {
            get {
                return ResourceManager.GetString("WouldYouLikeToEnableMsgText", resourceCulture);
            }
        }
        
        internal static string TouchIDFaceIDForMsgText {
            get {
                return ResourceManager.GetString("TouchIDFaceIDForMsgText", resourceCulture);
            }
        }
        
        internal static string authentificationQueMsgText {
            get {
                return ResourceManager.GetString("authentificationQueMsgText", resourceCulture);
            }
        }
        
        internal static string YesEnableMsgText {
            get {
                return ResourceManager.GetString("YesEnableMsgText", resourceCulture);
            }
        }
        
        internal static string NoLogInMsgText {
            get {
                return ResourceManager.GetString("NoLogInMsgText", resourceCulture);
            }
        }
        
        internal static string NAMECapText {
            get {
                return ResourceManager.GetString("NAMECapText", resourceCulture);
            }
        }
        
        internal static string SURNAMECapText {
            get {
                return ResourceManager.GetString("SURNAMECapText", resourceCulture);
            }
        }
        
        internal static string EMAILCapText {
            get {
                return ResourceManager.GetString("EMAILCapText", resourceCulture);
            }
        }
        
        internal static string SomethingNotRightLetUsKnowMsgText {
            get {
                return ResourceManager.GetString("SomethingNotRightLetUsKnowMsgText", resourceCulture);
            }
        }
        
        internal static string ClaimProfileText {
            get {
                return ResourceManager.GetString("ClaimProfileText", resourceCulture);
            }
        }
        
        internal static string ThankYouForYourRequestMsgText {
            get {
                return ResourceManager.GetString("ThankYouForYourRequestMsgText", resourceCulture);
            }
        }
        
        internal static string YouCanNowContinueSettingMsgText {
            get {
                return ResourceManager.GetString("YouCanNowContinueSettingMsgText", resourceCulture);
            }
        }
        
        internal static string UpYourProfileMsgText {
            get {
                return ResourceManager.GetString("UpYourProfileMsgText", resourceCulture);
            }
        }
        
        internal static string OnceYourCoordinatorHasMsgText {
            get {
                return ResourceManager.GetString("OnceYourCoordinatorHasMsgText", resourceCulture);
            }
        }
        
        internal static string ApprovedTheChangesYourMsgText {
            get {
                return ResourceManager.GetString("ApprovedTheChangesYourMsgText", resourceCulture);
            }
        }
        
        internal static string ProfileWillBeUploadedMsgText {
            get {
                return ResourceManager.GetString("ProfileWillBeUploadedMsgText", resourceCulture);
            }
        }
        
        internal static string ContinueSetupText {
            get {
                return ResourceManager.GetString("ContinueSetupText", resourceCulture);
            }
        }
        
        internal static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        internal static string TimeHeaderText {
            get {
                return ResourceManager.GetString("TimeHeaderText", resourceCulture);
            }
        }
        
        internal static string DescribeItWithSomeEmojisText {
            get {
                return ResourceManager.GetString("DescribeItWithSomeEmojisText", resourceCulture);
            }
        }
        
        internal static string PasswordMustIncludeMsgText {
            get {
                return ResourceManager.GetString("PasswordMustIncludeMsgText", resourceCulture);
            }
        }
        
        internal static string SubmitHeaderText {
            get {
                return ResourceManager.GetString("SubmitHeaderText", resourceCulture);
            }
        }
        
        internal static string AccessYourProfileByUsignYourCompanyEmailHeaderText {
            get {
                return ResourceManager.GetString("AccessYourProfileByUsignYourCompanyEmailHeaderText", resourceCulture);
            }
        }
        
        internal static string OrEnterTheIDYourCompanyProvidedHeaderText {
            get {
                return ResourceManager.GetString("OrEnterTheIDYourCompanyProvidedHeaderText", resourceCulture);
            }
        }
    }
}
