//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork.Multilingual {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AtWork.Multilingual.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string InternalServerErrorMsg {
            get {
                return ResourceManager.GetString("InternalServerErrorMsg", resourceCulture);
            }
        }
        
        internal static string UnauthorizedErrorMsg {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMsg", resourceCulture);
            }
        }
        
        internal static string RequestTimeoutErrorMsg {
            get {
                return ResourceManager.GetString("RequestTimeoutErrorMsg", resourceCulture);
            }
        }
        
        internal static string SomethingWentWrongText {
            get {
                return ResourceManager.GetString("SomethingWentWrongText", resourceCulture);
            }
        }
        
        internal static string TooManyAttemptsText {
            get {
                return ResourceManager.GetString("TooManyAttemptsText", resourceCulture);
            }
        }
        
        internal static string BackendErrorText {
            get {
                return ResourceManager.GetString("BackendErrorText", resourceCulture);
            }
        }
        
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        internal static string AlertOkText {
            get {
                return ResourceManager.GetString("AlertOkText", resourceCulture);
            }
        }
        
        internal static string NoInternetMsg {
            get {
                return ResourceManager.GetString("NoInternetMsg", resourceCulture);
            }
        }
        
        internal static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        internal static string StartWritingYourPost {
            get {
                return ResourceManager.GetString("StartWritingYourPost", resourceCulture);
            }
        }
        
        internal static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        internal static string CommentPlaceholderText {
            get {
                return ResourceManager.GetString("CommentPlaceholderText", resourceCulture);
            }
        }
        
        internal static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        internal static string AddImagesToYourPost {
            get {
                return ResourceManager.GetString("AddImagesToYourPost", resourceCulture);
            }
        }
        
        internal static string AddAttachFileToYourPost {
            get {
                return ResourceManager.GetString("AddAttachFileToYourPost", resourceCulture);
            }
        }
        
        internal static string StoragePermissionAlert {
            get {
                return ResourceManager.GetString("StoragePermissionAlert", resourceCulture);
            }
        }
        
        internal static string PermissionErrorText {
            get {
                return ResourceManager.GetString("PermissionErrorText", resourceCulture);
            }
        }
        
        internal static string EditCropButtonText
        {
            get
            {
                return ResourceManager.GetString("EditCropButtonText", resourceCulture);
            }
        }
        internal static string ChooseWhoCanSeeYourPost
        {
            get
            {
                return ResourceManager.GetString("ChooseWhoCanSeeYourPost", resourceCulture);
            }
        }
    }
}
