//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork.Multilingual {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AtWork.Multilingual.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string InternalServerErrorMsg {
            get {
                return ResourceManager.GetString("InternalServerErrorMsg", resourceCulture);
            }
        }
        
        internal static string UnauthorizedErrorMsg {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMsg", resourceCulture);
            }
        }
        
        internal static string RequestTimeoutErrorMsg {
            get {
                return ResourceManager.GetString("RequestTimeoutErrorMsg", resourceCulture);
            }
        }
        
        internal static string SomethingWentWrongText {
            get {
                return ResourceManager.GetString("SomethingWentWrongText", resourceCulture);
            }
        }
        
        internal static string TooManyAttemptsText {
            get {
                return ResourceManager.GetString("TooManyAttemptsText", resourceCulture);
            }
        }
        
        internal static string BackendErrorText {
            get {
                return ResourceManager.GetString("BackendErrorText", resourceCulture);
            }
        }
        
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        internal static string AlertOkText {
            get {
                return ResourceManager.GetString("AlertOkText", resourceCulture);
            }
        }
        
        internal static string NoInternetMsg {
            get {
                return ResourceManager.GetString("NoInternetMsg", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        public static string LoginEmptyFieldMsg
        {
            get
            {
                return ResourceManager.GetString("LoginEmptyFieldMsg", resourceCulture);
            }
        }
        public static string InvalidEmailMsg
        {
            get
            {
                return ResourceManager.GetString("InvalidEmailMsg", resourceCulture);
            }
        }
        public static string PasswordLengthMsg
        {
            get
            {
                return ResourceManager.GetString("PasswordLengthMsg", resourceCulture);
            }
        }
    }
}
